name: Browsertrix action
on:
  workflow_dispatch: # trigger manually
    inputs:
        url:
          description: 'Url to crawl'
          required: true

# globals
env:
# build artifacts
  WACZ_BUILD: wacz-build

jobs:
  crawl_url:
    runs-on: ubuntu-latest
    steps:
      
      - name: Create collection name
        run: |
          url=${{ github.event.inputs.url }}
          url=${url/http:\/\//}
          url=${url/https:\/\//}
          url=${url//\//_}
          echo url
          
          echo COLLECTION=url >> $GITHUB_ENV
      
      - name: Setup docker
        run: docker pull webrecorder/browsertrix-crawler
      
      - name: Crawl site
        run: docker run -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --url ${{ github.event.inputs.url }} --workers 16 --saveState always --generateWACZ --text --collection ${ COLLECTION }
     
      - run: ls -R
     
     # - name: Upload WACZ artifact
     #   uses: actions/upload-artifact@v2
     #   with:
     #     name: ${{ env.CLI_BUILD }}
     #     path: ${{ github.workspace }}/${{ env.WACZ_BUILD }}/cli.txt
